version: '3.8'


services:
  database:
    image: 'postgres:15.2'
    restart: always
    ports:
      - '5432:5432'
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_DB=movie-matrix'
      - 'POSTGRES_PASSWORD=postgres'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: